name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: >
        pip install -e '.[test]'
    - name: Test with pytest
      run: >
        pytest
    - name: Do static type checking with Mypy
      run: >
        mypy .
  darker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: akaihola/darker@gh-action-linters
      with:
        options: --verbose --check --diff --isort
        revision: origin/master...
        lint: flake8,pylint
